name: Maven - SBOM - DC - DT

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Dmaven.repo.local=.m2"
      DT_API_URL: ${{ secrets.DT_API_URL }}
      DT_API_KEY: ${{ secrets.DT_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # pom.xml лежит в myapp/
      - name: Build & generate SBOM
        working-directory: ./myapp
        run: mvn -B -ntp clean verify -DskipTests

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bom
          path: |
            myapp/target/bom.xml
            myapp/target/bom.json
          retention-days: 7

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          # чтобы контейнер не пытался использовать JAVA_HOME с хоста
          JAVA_HOME: ""
          JAVA_HOME_17_X64: ""
        with:
          project: ${{ github.repository }}
          path: ./myapp              # что сканировать
          format: "ALL"
          out: dependency-check-report  # КУДА писать отчёт (НЕ output!)

      - name: Upload DC report
        uses: actions/upload-artifact@v4
        with:
          name: dc-report
          path: dependency-check-report
          retention-days: 7

      - name: Upload SBOM to Dependency-Track
        run: |
          curl -s -X POST "$DT_API_URL/api/v1/bom" \
               -H "X-Api-Key: $DT_API_KEY" \
               -F "autoCreate=true" \
               -F "projectName=${{ github.repository }}" \
               -F "projectVersion=${{ github.head_ref || github.ref_name }}" \
               -F "bom=@myapp/target/bom.xml" | tee dt-upload.log

      - name: Upload Dependency-Track log
        uses: actions/upload-artifact@v4
        with:
          name: dt-upload-log
          path: dt-upload.log
          retention-days: 7
